### ISSUE TITLE
fixed marker and a variable marker can appear on the same field

### ISSUE THREAD

**Issue by Dekrid** [TrnsltLife/your-journey#31]
i noticed that a fixed marker and a variable marker can appear on the same field. This is not the case in the original game. Is it possible to change the algorithm so that this no longer occurs?

**Comment by TrnsltLife** [comment]
Partially fixed in v0.33. Fixed and random tokens will no longer overlap. They may still occasionally occur in the same space. You can avoid this by not using fixed and random tokens in the same tile block. Or to some extent by placing your fixed tokens as centrally as possible on the tile - tokens have a collision radius that will exclude random tokens in that area, so if you place it centrally, you have a better chance of avoiding this.
